"""empty message

Revision ID: 3a9745a06f20
Revises: 2a753c88cee2
Create Date: 2019-12-01 20:16:42.159600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9745a06f20'
down_revision = '2a753c88cee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('announcements', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('announcements', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'title')
    op.drop_column('announcements', 'body_html')
    op.drop_column('announcements', 'body')
    # ### end Alembic commands ###
